import { TaskInterface, TaskPriority } from '../types/task-interface';

export const TASKS_MOCK: TaskInterface[] = [
    {
        id: '1',
        title: 'Fix login bug',
        description: 'Resolve the login issue in production',
        creationDate: new Date('2025-02-20T10:00:00'),
        expirationDate: new Date('2025-02-25T18:00:00'),
        priority: TaskPriority.High,
    },
    {
        id: '2',
        title: 'Write unit tests',
        description: 'Cover 80% of the codebase with tests',
        creationDate: new Date('2025-02-21T09:30:00'),
        expirationDate: new Date('2025-02-26T17:00:00'),
        priority: TaskPriority.Medium,
    },
    {
        id: '3',
        title: 'Update documentation',
        description: 'Add API documentation for the new features',
        creationDate: new Date('2025-02-22T12:00:00'),
        expirationDate: new Date('2025-02-27T15:00:00'),
        priority: TaskPriority.Low,
    },
    {
        id: '4',
        title: 'Optimize database queries',
        description: 'Improve database performance by optimizing queries',
        creationDate: new Date('2025-02-23T08:45:00'),
        expirationDate: new Date('2025-02-28T14:00:00'),
        priority: TaskPriority.High,
    },
    {
        id: '5',
        title: 'Refactor authentication module',
        description: 'Simplify and modularize authentication code',
        creationDate: new Date('2025-02-24T14:20:00'),
        expirationDate: new Date('2025-03-01T11:30:00'),
        priority: TaskPriority.Medium,
    },
    {
        id: '6',
        title: 'Fix mobile responsiveness',
        description: 'Ensure proper layout and styling on mobile devices',
        creationDate: new Date('2025-02-25T10:10:00'),
        expirationDate: new Date('2025-03-02T19:00:00'),
        priority: TaskPriority.Urgent,
    },
    {
        id: '7',
        title: 'Improve API error handling',
        description: 'Implement better error messages and logging',
        creationDate: new Date('2025-02-26T15:00:00'),
        expirationDate: new Date('2025-03-03T13:45:00'),
        priority: TaskPriority.Low,
    },
    {
        id: '8',
        title: 'Implement dark mode',
        description: 'Add a dark theme option for better UX',
        creationDate: new Date('2025-02-27T09:30:00'),
        expirationDate: new Date('2025-03-04T17:15:00'),
        priority: TaskPriority.Medium,
    },
    {
        id: '9',
        title: 'Deploy new feature to production',
        description: 'Release the latest feature update',
        creationDate: new Date('2025-02-28T16:45:00'),
        expirationDate: new Date('2025-03-05T10:30:00'),
        priority: TaskPriority.High,
    },
    {
        id: '10',
        title: 'Migrate to new server',
        description: 'Move application to a more scalable infrastructure',
        creationDate: new Date('2025-03-01T11:00:00'),
        expirationDate: new Date('2025-03-06T14:00:00'),
        priority: TaskPriority.Urgent,
    },
    {
        id: '11',
        title: 'Fix logout bug',
        description: 'Ensure users can log out properly',
        creationDate: new Date('2025-03-02T13:20:00'),
        expirationDate: new Date('2025-03-07T18:00:00'),
        priority: TaskPriority.High,
    },
    {
        id: '12',
        title: 'Enhance search functionality',
        description: 'Improve search speed and accuracy',
        creationDate: new Date('2025-03-03T07:45:00'),
        expirationDate: new Date('2025-03-08T11:00:00'),
        priority: TaskPriority.Medium,
    },
    {
        id: '13',
        title: 'Add multi-language support',
        description: 'Enable language selection for international users',
        creationDate: new Date('2025-03-04T17:30:00'),
        expirationDate: new Date('2025-03-09T15:45:00'),
        priority: TaskPriority.Low,
    },
    {
        id: '14',
        title: 'Reduce bundle size',
        description:
            'Optimize webpack configuration for faster load times',
        creationDate: new Date('2025-03-05T14:10:00'),
        expirationDate: new Date('2025-03-10T13:30:00'),
        priority: TaskPriority.Medium,
    },
    {
        id: '15',
        title: 'Enhance security policies',
        description: 'Implement additional security measures',
        creationDate: new Date('2025-03-06T12:00:00'),
        expirationDate: new Date('2025-03-11T17:00:00'),
        priority: TaskPriority.Urgent,
    },
];

export default TASKS_MOCK;